config/routes.rb
Rails.application.routes.draw do
 
  root "agents#index"

  resources :agents do
    resources :contacts
  end

end

app/models/agent.rb
class Agent < ActiveRecord::Base
	has_many :contacts
	after_create :create_default_contact

	validates :name, presence: true
	validates :tel, presence: true

	def create_default_contact
		self.contacts.create({ :name => "default_contact:Andy", :email => "andy@gmail.com" })
	end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	belongs_to :agent
	validates :name, presence: true
	validates :email, presence: true

end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  def index
  	@agents = Agent.all
  end

  def show
  	@agent = Agent.find(params[:id])
  	@contacts = @agent.contacts.all

  end

  def new
  	@agent = Agent.new
  end

  def create
  	@agent = Agent.new(agent_params)
  	if @agent.save
  		flash[:warning] = "Success!"
  		redirect_to agents_path
  	else
  		flash[:warning] = "Fail!:#{@agent.errors.full_messages}"
  		render :new
  	end

  end

  def edit
  	@agent = Agent.find(params[:id])
  end

  def update
  	@agent = Agent.find(params[:id])
  	
  	if @agent.update_attributes(agent_params)
  		flash[:warning] = "Success!"
  		redirect_to agents_path
  	else	
  		flash[:warning] = "Fail!:#{@agent.errors.full_messages}"
  		render :edit
  	end 

  end

  def destroy
  	@agent = Agent.find(params[:id])
  	@agent.destroy
  	redirect_to agents_path
  end

private

	def agent_params
		params.require("agent").permit(:name, :tel)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	before_action :find_agent

  def index
  	@contacts = @agent.contacts.all
  end

  def new
  	@contact = @agent.contacts.new
  end

  def show
  	@contact = @agent.contacts.find(params[:id])
  end

  def edit
		@contact = @agent.contacts.find(params[:id])
  end

  def update
  	@contact = @agent.contacts.find(params[:id])

  	if @contact.update_attributes(contacts_params)
  		flash[:warning] = "Success!"
  		redirect_to agent_contacts_path(@agent)
  	else
  		flash[:warning] = "Fail!:#{@contact.errors.full_messages}"
  		render :edit
  	end
  end

  def create
  	@contact = @agent.contacts.new(contacts_params)

  	if @contact.save
  		flash[:warning] = "Success!"
  		redirect_to agent_contacts_path(@agent)
  	else
  		flash[:warning] = "Fail!#{@contact.errors.full_messages}"
  		render :new
  	end
  end

  def destroy
  	@contact = @agent.contacts.find(params[:id])
  	@contact.destroy
  	redirect_to agent_contacts_path(@agent)
  end

private

	def find_agent
		@agent = Agent.find(params[:agent_id])
	end

	def contacts_params
		params.require(:contact).permit(:name, :email)		
	end

end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/agents/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">New Agent</h3>
  </div>
  <div class="panel-body">
		<%= form_for @agent do |f| %>
			<p>
				<%= f.label :name, "Name" %>
				<%= f.text_field :name, :class => "form-control" %>
			</p>
			<p>
				<%= f.label :tel, "TEL" %>
				<%= f.text_field :tel, :class => "form-control" %>
			</p>
			<p>
				<%= f.submit "Update", :class => "btn btn-default"  %>
			</p>
		<% end %>
	</div>
</div>

app/views/agents/index.html.erb
<table class="table">
	<tbody>
		<tr>		
			<th>ID</th>
			<th>Name</th>
			<th>TEL</th>
			<th>SHOW</th>
			<th>UPDATE</th>
			<th>DELETE</th>
			<th>CONTACTS</th>
		</tr>
		<% @agents.each do |agent|%>
			<tr>
				<td><%= agent.id %></td>
				<td><%= agent.name %></td>
				<td><%= agent.tel %></td>	
				<td><%= link_to "show", agent_path(agent), :class => "btn btn-info" %></td>
				<td><%= link_to "update", edit_agent_path(agent), :class => "btn btn-success"  %></td>
				<td><%= link_to "destroy", agent_path(agent), method: :delete, data: { :confirm => "Are you sure?" }, :class => "btn btn-danger"  %></td>
				<td><%= link_to "Contacts", agent_contacts_path(agent), :class => "btn btn-warning" %></td>
			</tr>
		<% end %>
	<tbody>
</table>

<p>
	<%= link_to "New Agent", new_agent_path, :class => "btn btn-lg btn-primary" %>
</p>

app/views/agents/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">New Agent</h3>
  </div>
  <div class="panel-body">
		<%= form_for @agent do |f| %>
			<p>
				<%= f.label :name, "Name" %>
				<%= f.text_field :name, :class => "form-control" %>
			</p>
			<p>
				<%= f.label :tel, "TEL" %>
				<%= f.text_field :tel, :class => "form-control" %>
			</p>
			<p>
				<%= f.submit "Add", :class => "btn btn-default"  %>
			</p>
		<% end %>
	</div>
</div>

app/views/agents/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Agent Information</h3>
  </div>
  <div class="panel-body">
		<p><strong>ID:</strong> <%= @agent.id %></p>
		<p><strong>NAME:</strong> <%= @agent.name %></p>
		<p><strong>TEL:</strong> <%= @agent.tel %></p>
		<p><%= link_to "Show Contacts", agent_contacts_path(@agent), :class => "btn btn-lg btn-primary" %></p>
	</div>
</div>
	

app/views/contacts/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">New Agent</h3>
  </div>
  <div class="panel-body">
		<%= simple_form_for [@agent, @contact] do |f| %>
			<p>
				<%= f.label :name, "Name" %>
				<%= f.text_field :name, :class => "form-control" %>
			</p>
			<p>
				<%= f.label :email, "Email" %>
				<%= f.text_field :email, :class => "form-control" %>
			</p>
			<p>
				<%= f.submit "Update", :class => "btn btn-default"  %>
			</p>
		<% end %>
	</div>
</div>

app/views/contacts/index.html.erb
<h1>All contacts of agent : <%= @agent.name %></h1>
<table class="table">
	<tr>
		<th>NAME</th>
		<th>EMAIL</th>
		<th>SHOW</th>
		<th>UPDATE</th>
		<th>DELETE</th>
	</tr>
	<% @contacts.each do |contact| %>
		<tr>
			<td><%= contact.name%></td>
			<td><%= contact.email %></td>
			<td><%= link_to "show", agent_contact_path(contact.agent, contact), :class => "btn btn-info"  %>
			<td><%= link_to "update", edit_agent_contact_path(contact.agent, contact), :class => "btn btn-success" %></td>
			<td><%= link_to "destroy", agent_contact_path(contact.agent, contact), method: :delete, data: { :confirm => "Are you sure?" }, :class => "btn btn-danger"   %></td>
		</tr>
	<% end %>
</table>

<p><%= link_to "Back To Agent List", agents_path, :class => "btn btn-lg btn-primary" %></p>
<p><%= link_to "New Contact", new_agent_contact_path(@agent), :class => "btn btn-lg btn-primary" %></p>

app/views/contacts/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">New Contact</h3>
  </div>
  <div class="panel-body">
		<%= simple_form_for [@agent, @contact] do |f| %>
			<p>
				<%= f.label :name, "Name" %>
				<%= f.text_field :name, :class => "form-control" %>
			</p>
			<p>
				<%= f.label :email, "Email" %>
				<%= f.text_field :email, :class => "form-control" %>
			</p>
			<p>
				<%= f.submit "Add", :class => "btn btn-default"  %>
			</p>
		<% end %>
	</div>
</div>

app/views/contacts/show.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    <h3 class="panel-title">Contact Information</h3>
  </div>
  <div class="panel-body">
		<p><strong>NAME:</strong> <%= @contact.name %></p>
		<p><strong>EMAIL:</strong> <%= @contact.email %></p>
		<p><%= link_to "Back", agent_contacts_path(@agent), :class => "btn btn-lg btn-primary" %></p>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppOk</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		    <!-- Static navbar -->
      <div class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">APP-OK</a>
          </div>
          <div class="navbar-collapse collapse">
            
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </div>
      <% if flash[:warning] %>
      	<div class="alert fade in alert-success"><a class="close" data-dismiss="alert" href="#">x</a>
        	<%= flash[:warning] %>
      	</div>
    	<% end %>
		<%= yield %>
	</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
</body>
</html>